mysql_root_password: 12345
mysql_databases:
  - name: notes
    enconding: latin1
    collation: utf8_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: 12345
    priv: "notes.*:ALL"